= LOD Prepare
Benno Bielmeier <benno.bielmeier@st.oth-regensburg.de>
:icons: font

This repository is a component of the author's bachelor thesis.
It focuses the "`data preparation`" step of an machine learning (_ML_) pipeline.
More precisely this component takes raw sensor measurements and transform them to frequency space using the https://en.wikipedia.org/wiki/Fast_Fourier_transform[FFT].
The measurement values are retrieved from a table named `measured_values` of a certain database.
The FFT results are inserted into table `training_data` of the same database.

Besides the _main_ package `lod-prepare` (that does the above mentioned FFT transformation) a workspace name `build-db` can be found in this project.
It provides a handy way to insert some well-defined dummy data into the mentioned table `measured_values` of an empty, pre-existing database.

== Setup

[IMPORTANT]
.Prerequisites
================================================================================
* https://www.rust-lang.org/learn/get-started[Rust] (v1.48.0) +
(Dependency Management: https://doc.rust-lang.org/cargo/index.html[`cargo`])
* https://www.sqlite.org[SQLite3] (v3.33.0)
* pre-existing, empty database
================================================================================

[NOTE]
================================================================================
Hereinafter the String `DB_PATH` should be replaced by your database location:
e.g. `cargo run DB_PATH` -> `cargo run ./db/measurements.db`
================================================================================

. Checkout project
+
[source, shell]
git clone git@github.com:bbenno/LOD-prepare.git
cd LOD-prepare
. Build project
+
[source, shell]
cargo build
. (optional) Build and fill dummy database
+
[source, shell]
------------------------------
./rebuild-dummy-db.sh
------------------------------
. Run data transformation
+
[source, shell]
cargo run DB_PATH
. (optional) Show transformed data
[source, shell]
sqlite3 -readonly -box DB_PATH
