= LOD Prepare
Benno Bielmeier <benno.bielmeier@st.oth-regensburg.de>
:icons: font

This repository contains one component of the author's bachelor thesis.
It focuses the "`data preparation`" step of an machine learning (_ML_) pipeline.
More precisely this componet takes raw sensor measurments and transform them to frequency space using the https://en.wikipedia.org/wiki/Fast_Fourier_transform[FFT].

== Setup

[IMPORTANT]
.Prerequirements
================================================================================
* https://www.rust-lang.org[Rust] installed
* https://www.sqlite.org[SQLite3] installed
* created but yet empty database in the parent folder `../measurements.db`
================================================================================

TIP: Want to set up the entire development environment? Have a look at mine in link:tooling.adoc[Tooling] document.

[NOTE]
================================================================================
Hereinafter the String `DB_PATH` should be replaced by your database location:
e.g. `cargo run DB_PATH` -> `cargo run ../measurements.db`
================================================================================

. Checkout project
+
[source, shell]
git clone git@github.com:bbenno/LOD-prepare.git
cd LOD-prepare
. Build project
+
[source, shell]
cargo build
. (optional) Build and fill dummy database
+
[source, shell]
------------------------------
./rebuild-dummy-db.sh
------------------------------
. Run data transformation
+
[source, shell]
cargo run DB_PATH
. (optional) Show transformed data
[source, shell]
sqlite3 -readonly -box DB_PATH
